Quests:
  1:
    Name: "击杀五只僵尸"
    Description: "击杀五只僵尸"
    Type: "KILL"
    Entity: "ZOMBIE"
    Amount: 5
  2:
    Name: "获取一组苹果"
    Description: "获取一组苹果"
    Type: "ITEM"
    Item: 1
    Amount: 64
  3:
    Name: "获取一组木头"
    Description: "获取一组木头"
    Type: "DIG"
    BlockType: 1
    Amount: 64
  4:
    Name: "获取一组钻石"
    Description: "获取一组钻石"
    Type: "ITEM"
    Item: 264
    Amount: 64
Date: ""

n1:
  - "原木x128"
  - "17"
  - "give %player% 17 128"
n2:
  - "无"
  - "ICON"
  - ""
n3:
  - "岩浆桶x2"
  - "327"
  - "give %player% 327 2"
n4:
  - "无"
  - "ICON"
  - ""
n5:
  - "水下呼吸10 铁盔[海底行者]"
  - "306"
  - "ITEM:3:1"
n6:
  - "无"
  - "ICON"
  - ""
n7:
  - "无"
  - "ICON"
  - ""
n8:
  - "村民刷怪蛋x2"
  - "383"
  - "ITEM:7:2"
n9:
  - "无"
  - "ICON"
  - ""
n10:
  - "无"
  - "ICON"
  - ""
n11:
  - "火焰保护10 铁盔【烈焰行者】"
  - "306"
  - "ITEM:5:1"
n12:
  - "哞菇牛蛋x2"
  - "383"
  - "ITEM:10:2"
n13:
  - "无"
  - "ICON"
  - ""
n14:
  - "无"
  - "ICON"
  - ""
n15:
  - "无"
  - "ICON"
  - ""
n16:
  - "无"
  - "ICON"
  - ""
n17:
  - "无"
  - "ICON"
  - ""
n18:
  - "无"
  - "ICON"
  - ""
n19:
  - "无"
  - "ICON"
  - ""
n20:
  - "经验瓶x64"
  - "384"
  - "give %player% 384 64"
n21:
  - "摔落保护10 铁靴【高空行者】"
  - "309"
  - "ITEM:6:1"
n22:
  - "经验瓶x256"
  - "384"
  - "give %player% 384 256"
n23:
  - "无"
  - "ICON"
  - ""
n24:
  - "牛刷怪笼x1"
  - "52"
  - "ITEM:8:1"
n25:
  - "无"
  - "ICON"
  - ""
n26:
  - "哞菇牛刷怪笼x1 "
  - "52"
  - "ITEM:9:1"
n27:
  - "无"
  - "ICON"
  - ""
n28:
  - "无"
  - "ICON"
  - ""
n29:
  - "龙首x1"
  - "397:5"
  - "give %player% 397:5 1"
n30:
  - "无"
  - "ICON"
  - ""
n31:
  - "无"
  - "ICON"
  - ""

v1:
  - "水桶x3 岩浆桶x3"
  - "326"
  - "give %player% 326 3"
  - "give %player% 327 3"
v2:
  - "精准采集1耐久3钻镐x1【精锐镐】 ★"
  - "278"
  - "ITEM:1:1"
v3:
  - "附魔台x1"
  - "116"
  - "give %player% 116 1"
v4:
  - "效率5耐久3钻斧【开山斧】★"
  - "279"
  - "ITEM:2:1"
v5:
  - "经验瓶x256"
  - "384"
  - "give %player% 384 256"
v6:
  - "钓饵3 海之眷顾3 耐久3【钓竿】★"
  - "346"
  - "ITEM:11:1"
v7:
  - "猪刷怪笼x1 ★"
  - "52"
  - "ITEM:12:1"
v8:
  - "守卫者刷怪笼x1 ★"
  - "52"
  - "ITEM:13:1"
v9:
  - "无"
  - "ICON"
  - ""
v10:
  - "锋利5掠夺3耐久3钻石剑x1【收割者】★"
  - "276"
  - "ITEM:4:1"
v11:
  - "僵尸刷怪笼x1 ★"
  - "52"
  - "ITEM:14:1"
v12:
  - "菌丝方块x64 ★"
  - "110"
  - "give %player% 110 64"
v13:
  - "无"
  - "ICON"
  - ""
v14:
  - "凋零骷髅头x2 ★"
  - "397:1"
  - "give %player% 397:1 2"
v15:
  - "经验修补技能书 ★"
  - "403"
  - "ITEM:15:1"
v16:
  - "凋零骷髅头x2 ★"
  - "397:1"
  - "give %player% 397:1 2"
v17:
  - "经验瓶x256"
  - "384"
  - "give %player% 384 256"
v18:
  - "无"
  - "ICON"
  - ""
v19:
  - "无"
  - "ICON"
  - ""
v20:
  - "经验瓶x256"
  - "384"
  - "give %player% 384 256"
v21:
  - "潜影盒x1"
  - "219"
  - "give %player% 219 1"
v22:
  - "无"
  - "ICON"
  - ""
v23:
  - "粘液球x32 ★"
  - "341"
  - "give %player% 341 32"
v24:
  - "凋零骷髅头x2 ★"
  - "397:1"
  - "give %player% 397:1 2"
v25:
  - "无"
  - "ICON"
  - ""
v26:
  - "经验瓶x256"
  - "384"
  - "give %player% 384 256"
v27:
  - "无"
  - "ICON"
  - ""
v28:
  - "村民刷怪笼x1 ★"
  - "52"
  - "ITEM:16:1"
v29:
  - "经验瓶x256"
  - "384"
  - "give %player% 384 256"
v30:
  - "鞘翅x1★"
  - "443"
  - "give %player% 443 1"
v31:
  - "无"
  - "ICON"
  - ""

DBUrl: "47.96.248.18"
DBUserName: "root"
DBPassWord: "18277229825"
DBInitPoolSize: 10
DBMaxPoolSize: 50
DBMinPoolSize: 5